### ISSUE TITLE
Здраствуйте Tim System

### ISSUE THREAD

**Issue by Inmutef** [TiM-SyStEm/Special-Key-SPS#23]
**Здраствуйте Tim System как можно связать с вами : Gmail,Telegram желательно Gmail**

**Comment by Inmutef** [comment]
Moй GMAIL : inmutefgames@gmail.com

**Comment by Inmutef** [comment]
Спасибо что ответили надеюсь прочитаете моё сообщение которое я вам отправил на ваш GMAIL

**Comment by TiM-SyStEm** [comment]
Да прочитаю
